### ISSUE TITLE
Incorect licencing for utilized databases

### ISSUE THREAD

**Issue by BelleNottelling** [safing/mmdbmeld#1]
Hi there, I hope you're doing well!

Great little project you've got here, I'm utilizing it to automate the build process of various databases and it's working well.
This issue is really just an FYI for you, but your readme states "Default sources are CC0" which isn't actually true.

The [asn-ipv6.csv](https://cdn.jsdelivr.net/npm/@ip-location-db/asn/asn-ipv6.csv) database your script pulls in is under the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license and does differ from CC0. CC BY 4.0 **does** require attribution to be given.

I assume you mistakenly grabbed that instead of [iptoasn-asn-ipv4.csv](https://cdn.jsdelivr.net/npm/@ip-location-db/iptoasn-asn/iptoasn-asn-ipv4.csv) which is under the [PDDL](https://opendatacommons.org/licenses/pddl/1-0/) license and as such doesn't require attribution much like the CC0 license. (both CC0 and PDDL state the material is considered public domain)

However even then, stating that it's CC0 is still technically incorrect.

Edit to be clear:
Both the IPv4 and IPv6 DBs are utilized and have the same license, I only referenced one of the file names for simplicity

**Comment by dhaavi** [comment]
Hey @BelleNottelling,

Thanks! I just created this last week. Nice to see someone already using it!

Yes, you are right, I got this mixed up. I myself use other sources, but wanted to use public sources in the example so that people will have to more actively check sources and licenses if they want better data.

I switched to the iptoasn source in the referenced commit.

**Comment by BelleNottelling** [comment]
Cheers!

Thanks again for the project!
